language: generic
python:
  - "3.5"
cache:
  - pip
install:
  - pip install --user awscli
deploy:
  provider: s3
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_KEY
  bucket: $BUCKET
  skip_cleanup: true
  region: "eu-west-1"
  local_dir: build
  on:
    branch: production
after_deploy:
  - aws configure set aws_access_key_id $ACCESS_KEY
  - aws configure set aws_secret_access_key $SECRET_KEY
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
