baseURL = 'https://www.rorycaraher.com/'
languageCode = 'en-us'
title = 'Rory Caraher'
theme = 'rorycaraher'
copyright = '© 2026 Rory Caraher'
disableKinds = ['taxonomy', 'term']

[params]
  github = "https://github.com/rorycaraher/"
  soundcloud = "https://soundcloud.com/corner_nltl/"

[[menus.main]]
name = 'Home'
url = '/'
weight = 1

[[menus.main]]
name = 'Work'
url = '/work/'
weight = 2

[[menus.main]]
name = 'Extras'
url = '/extras/'
weight = 3
