#!/usr/bin/env bash
set -euo pipefail

GITHUB_USER="${GITHUB_USER:-rorycaraher}"
OUTPUT_FILE="${OUTPUT_FILE:-data/projects.yaml}"

query='query($login: String!) {
  user(login: $login) {
    pinnedItems(first: 6, types: REPOSITORY) {
      nodes {
        ... on Repository {
          name
          description
          url
          homepageUrl
          repositoryTopics(first: 10) {
            nodes { topic { name } }
          }
        }
      }
    }
  }
}'

body=$(jq -n --arg q "$query" --arg login "$GITHUB_USER" '{query: $q, variables: {login: $login}}')

response=$(curl -sf \
  -H "Authorization: Bearer ${GITHUB_TOKEN}" \
  -H "Content-Type: application/json" \
  -X POST \
  -d "$body" \
  https://api.github.com/graphql)

count=$(echo "$response" | jq '.data.user.pinnedItems.nodes | length')

{
  printf '# Auto-generated by scripts/fetch-projects.sh — do not edit manually\n\n'
  echo "$response" | jq -r '
    def quote: "\"" + gsub("\""; "\\\"") + "\"";
    .data.user.pinnedItems.nodes[] |
    [
      "- name: " + (.name | quote),
      "  description: " + ((.description // "" | if . == "" then "No description provided" else . end) | quote),
      "  url: " + (.url | quote)
    ] +
    (if .homepageUrl != null and .homepageUrl != "" then ["  homepage: " + (.homepageUrl | quote)] else [] end) +
    (if (.repositoryTopics.nodes | length) > 0
      then ["  tags:"] + (.repositoryTopics.nodes | map("    - " + .topic.name))
      else ["  tags: []"]
    end) +
    [""]
    | join("\n")
  '
} > "$OUTPUT_FILE"

echo "Wrote $count projects to $OUTPUT_FILE"
