#!/usr/bin/env bash
set -euo pipefail

GITHUB_USER="${GITHUB_USER:-rorycaraher}"
OUTPUT_FILE="${OUTPUT_FILE:-data/projects.yaml}"
TOPIC="portfolio"

response=$(curl -sf \
  -H "Authorization: Bearer ${GITHUB_TOKEN}" \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "https://api.github.com/search/repositories?q=topic:${TOPIC}+user:${GITHUB_USER}&sort=updated&per_page=100")

count=$(echo "$response" | jq '.total_count')

{
  printf '# Auto-generated by scripts/fetch-projects.sh — do not edit manually\n\n'
  echo "$response" | jq -r '
    def quote: "\"" + gsub("\""; "\\\"") + "\"";
    .items[] |
    [
      "- name: " + (.name | quote),
      "  description: " + ((.description // "" | if . == "" then "No description provided" else . end) | quote),
      "  url: " + (.html_url | quote)
    ] +
    (if .homepage != null and .homepage != "" then ["  homepage: " + (.homepage | quote)] else [] end) +
    (if (.topics | length) > 0
      then ["  tags:"] + (.topics | map("    - " + .))
      else ["  tags: []"]
    end) +
    [""]
    | join("\n")
  '
} > "$OUTPUT_FILE"

echo "Wrote $count projects to $OUTPUT_FILE"
